### ISSUE TITLE
Intertesting but doesn't open

### ISSUE THREAD

**Issue by EjectSteve** [naice/OpenTXLog2GoogleEarth#3]
I tried it on a Windows 10 machine, double click on OpenTXLog2GoogleEarth.exe and no window opens.  Nothing happens. Am I opening it wrong, is there a prerequisite that has to be installed first?  Thanks.

{
  "PathColor": "991081f4",
  "AltitudeMode": "relativeToGround",
  "AltitudeOffset": 0.0,
  "GoogleEarthExe": "C:\\Program Files\\Google\\Google Earth Pro\\client\\googleearth.exe",
  "GPSHeader": "GPS",
  "GPSSpeedHeader": "GSpd(kmh)",
  "GPSSpeedFactor": 1,
  "GPSSpeedLabel": "km/h",
  "AltitudeHeader": "Alt(m)",
  "TimeHeader": "Time",
  "DateHeader": "Date"
}

Actual googleearth location on my machine appears to be the same
C:\Program Files\Google\Google Earth Pro\client\googleearth.exe

**Comment by EjectSteve** [comment]
Maybe this helps:
c:\Movie\OpenTXLogs\release_win\Release\netcoreapp3.0>opentxlog2googleearth.exe razor.csv
or
c:\Movie\OpenTXLogs\release_win\Release\netcoreapp3.0>opentxlog2googleearth.exe

Gives:
A fatal error occurred. The required library hostfxr.dll could not be found.
If this is a self-contained application, that library should exist in [c:\Movie\OpenTXLogs\release_win\Release\netcoreapp3.0\].
If this is a framework-dependent application, install the runtime in the global location [C:\Program Files\dotnet] or use the DOTNET_ROOT environment variable to specify the runtime location or register the runtime location in [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x64\InstallLocation].

.net 4.8 is installed on my machine

**Comment by naice** [comment]
You need to install .net core runtime in Order to run .net core apps

**Comment by EjectSteve** [comment]
Installing .NET Core 3.1 SDK (v3.1.404)  worked fine.  Thank you.

**Comment by naice** [comment]
No problem, I should update the readme arccordingly :)
